spring:
  application:
    name: sample-api
  profiles:
    active: docker

---
spring:
  security:
    basic:
      enabled: {SPRING_SECURITY_BASIC_ENABLED}
    user:
      name: {SPRING_SECURITY_USER_NAME}
      password: {SPRING_SECURITY_USER_PASSWORD}

server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework
  servlet:
    context-path: ${SERVER_SERVELT_CONTEXT_PATH}

parse:
  application:
    id: {PARSE_APPLICATION_ID}
  resti-api:
    key: {PARSE_RESTIAPI_KEY}