FROM openjdk:11-jdk-slim
ARG JAR_FILE=target/*.jar
ENV SERVER_PORT=${SERVER_PORT:-8080} \
    SERVER_SERVELT_CONTEXT_PATH=${SERVER_SERVELT_CONTEXT_PATH:-'/v1/sample'} \
    PARSE_APPLICATION_ID=${PARSE_APPLICATION_ID:-8090} \
    PARSE_RESTIAPI_KEY=${PARSE_RESTIAPI_KEY:-8090} \
	TZ=America/Sao_Paulo
COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]