spring:
  application:
    name: sample-api
  profiles:
    active: default

---
spring:
  security:
    basic:
      enabled: false

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: '/v1/sample-api'

parse:
  application:
    id: {PARSE_APPLICATION_ID}
  resti-api:
    key: {PARSE_RESTIAPI_KEY}