name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.versionName }}

      - name: Initialize mandatory git config
        run: |
          git config user.name ${{ github.actor }}
          git config user.email moreira_rob@hotmail.com

      - name: Update Version in pom.xml
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.versionName }} -DgenerateBackupPoms=false

      - name: Commit pom.xml
        id: make-commit
        run: |
          git add pom.xml
          git commit --message "Prepare release ${{ github.event.inputs.versionName }}"

      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.versionName }}
#        run: |
#          git remote set-url --push origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git