name: Update Project Version

on: create

jobs:
  get-release:
    name: Get the release branch version number
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Get Version Name
        uses: bhowell2/github-substring-action@1.0.2
        id: version-name
        with:
          value: ${{ steps.branch-name.outputs.current_branch }}
          index_of_str: "release/"

      - name: Update Version in pom.xml
        run: mvn -B versions:set -DnewVersion=${{ steps.version-name.outputs.substring }} -DgenerateBackupPoms=false

      - name: Initialize Mandatory git Config
        run: |
          git config user.name ${{ github.actor }}
          git config user.email moreira_rob@hotmail.com

      - name: Commit and Push
        id: make-commit
        run: |
          git add pom.xml
          git commit --message "Update api Version"
          git remote set-url --push origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

#      - name: Push new branch
#        run: git push origin ${{ steps.branch-name.outputs.current_branch }}
#        run: |
#          git remote set-url --push origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}